# site_name: 'My notes'
site_description: Infosec-Notes
site_author: julianhal

repo_url: https://github.com/julianhal/notes

site_name: Notes

theme:
  name: material
  palette:
    scheme: slate

#theme: 'windmill-dark'
#    name: null
#    custom_dir: mkdocs_windmill_dark
#    # default from mkdocs_theme.yml
#    static_templates:
#        - 404.html
#    include_search_page: true
#    search_index_only: true
#    history_buttons: true
#    article_nav_top: true
#    article_nav_bottom: true

markdown_extensions:
  - toc:
      permalink: '#'

extra:
  history_buttons: true
  version: v1.0.0
